version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt
      - ./data:/usr/share/nginx/html
    restart: always
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./data:/data/letsencrypt
    command: certonly --webroot
      --webroot-path=/data/letsencrypt
      -d howell.haus 
      --email mjmaurer777@gmail.com 
      --agree-tos
      --non-interactive
    restart: 'no'
    depends_on:
      - nginx
  certbot-auto:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./data:/data/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 24h & wait $${!}; done;'"
    restart: always
    depends_on:
      - certbot
