version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf.conf:/etc/nginx/templates/nginx.conf.conf
      - ./certs:/etc/letsencrypt
      - ./data:/usr/share/nginx/html
    restart: always
    depends_on:
      certbot:
        condition: service_completed_successfully
    environment:
      DOMAIN: ${DOMAIN}
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
    networks:
        main:
            aliases:
                - nginx
  vouch:
    image: quay.io/vouch/vouch-proxy:latest
    volumes:
      - ./vouch-config.yml:/config/config.yml
    container_name: vouch
    depends_on:
      - nginx
    ports:
      - '9090:9090'
    restart: always
    environment:
      - VOUCH_DOMAINS
      - VOUCH_WHITELIST
      - VOUCH_COOKIE_DOMAIN
      - VOUCH_DOCUMENT_ROOT
      - OAUTH_CALLBACK_URL
      - OAUTH_CLIENT_ID
      - OAUTH_CLIENT_SECRET
    networks:
        main:
            aliases:
                - vouch
  certbot:
    image: certbot/certbot:latest
    container_name: certbot-initial
    ports:
      - '80:80'
    volumes:
      - ./certs:/etc/letsencrypt
      - ./data:/data/letsencrypt
    command: certonly -d ${DOMAIN} --standalone --non-interactive --agree-tos -m mjmaurer777@gmail.com
    restart: 'no'
    environment:
      - DOMAIN
  certbot-auto:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./data:/data/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 24h & wait $${!}; certbot renew --webroot --webroot-path=/data/letsencrypt ; done;'"
    restart: always
    depends_on:
      - nginx
    environment:
      - DOMAIN

networks:
  main: